name: trocaderoshop
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.2.1
  firebase_storage: ^12.1.3
  firebase_auth: ^5.1.4
  uuid: ^4.4.2
  intl: ^0.19.0
  image_picker: ^1.1.2
  simple_gradient_text: ^1.3.0
  provider: ^6.1.2
  google_maps_flutter: ^2.9.0
  location: ^7.0.0
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
